# Generated by Django 5.2.7 on 2026-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_totp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
